name = "advent23"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["advent23"]

[build-switches]
development.optimization = ["-Og", "-g", "-gnata"]
release.optimization = ["-O3", "-march=native", "-gnata", "-gnatn"]

[[depends-on]]
chests = "~0.1.1"
