name = "advent2020"
description = "Advent of Code 2020"
version = "1.0.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["advent2020"]
[[depends-on]]  # Added by alr
gnat_native = "^11.2.2"  # Added by alr
