name = "advent2022"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["advent2022"]

[build-switches]
release.optimization = ["-O3", "-gnatn", "-gnatp", "-march=native"]
[[depends-on]]
synack_misc = "~0.1.0"
[[pins]]
synack_misc = { url='https://github.com/JeremyGrosser/synack_misc' }
[[depends-on]]
ansiada = "^1.0.0"
[[depends-on]]
chests = "~0.1.1"
