name = "advent2021"
description = "Advent of Code 2021"
version = "0.0.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = [
    "d1_1",
    "d1_2",
    "d2_1",
    "d2_2",
    "d3_1",
    "d3_2"
]
