name = "day1_1"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["day1_1"]
[[depends-on]]
advent_io = "~0.1.0-dev"
[[pins]]
advent_io = { path='../advent_io' }
